name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Type check all packages
        run: pnpm run type-check

      - name: Lint all packages
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format:check

      - name: Test all packages
        run: pnpm run test

      - name: Build all packages (dependency-aware)
        run: pnpm run build
